<a href="https://colab.research.google.com/github/NguyenPhuoc1207/Baitap/blob/Pythoncoban/dataset_fisher's_iris_svm_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Dataset fisher's iris svm model


SVM là một thuật toán giám sát, nó có thể sử dụng cho cả việc phân loại hoặc đệ quy. Tuy nhiên nó được sử dụng chủ yếu cho việc phân loại. Trong thuật toán này, chúng ta vẽ đồi thị dữ liệu là các điểm trong n chiều ( ở đây n là số lượng các tính năng bạn có) với giá trị của mỗi tính năng sẽ là một phần liên kết.
Dưới đây là bài toán phân loại hoa dựa vào tập dữ liệu Fisher's 

In [12]:
#SVM on the Fisher's Iris Data set

import pandas as pd
import numpy as np

In [13]:
#ignore warnings
import warnings
warnings.filterwarnings('ignore')




Tải bộ dữ liệu mống mắt từ bộ dữ liệu dựng sẵn của sklearn


In [14]:
#load the iris data set from sklearn's in-built datasets
from sklearn.datasets import load_iris
iris = load_iris()

iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [15]:
print(iris['target_names'])

['setosa' 'versicolor' 'virginica']


Tạo DataFrame cho các tính năng


In [16]:
#create a DataFrame for the features
iris_feat = pd.DataFrame(iris['data'],columns=iris['feature_names'])
iris_feat.head(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2

Import train_test_split

Nguồn: [thư viện](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

In [17]:
#train test split with random_state=101 so that we get the same results
from sklearn.model_selection import train_test_split
X = iris_feat
y = iris['target']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [18]:
#importing the Support Vector Classifier, instantiating, fitting the model and predicting
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)
pred = model.predict(X_test)

In [19]:
#see how the model performed
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[13  0  0]
 [ 0 19  1]
 [ 0  0 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.95      0.97        20
           2       0.92      1.00      0.96        12

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



### Tối ưu mô hình

In [22]:


from sklearn.model_selection import GridSearchCV

C_grid = [0.1,1,10,100,1000]
gamma_grid = [1,0.1,0.01,0.001,0.0001]
param_grid = {'C':C_grid, 'gamma':gamma_grid}
grid = GridSearchCV(SVC(),param_grid,verbose=2)

In [23]:
grid.fit(X_train,y_train)


Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ..................................C=0.1, gamma=0.01; total time=   0.0s
[CV] END ..................................C=0.

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
             verbose=2)

In [24]:
#best parameter values
grid.best_params_

{'C': 1, 'gamma': 0.1}

In [25]:
grid.best_estimator_

SVC(C=1, gamma=0.1)

In [26]:
grid_pred = grid.predict(X_test)

In [27]:
print(confusion_matrix(y_test,grid_pred))

[[13  0  0]
 [ 0 19  1]
 [ 0  0 12]]


#### Kết quả tối ưu

In [28]:
print(classification_report(y_test,grid_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.95      0.97        20
           2       0.92      1.00      0.96        12

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

